# Generated by Django 4.0.3 on 2022-03-30 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0002_remove_usuarios_id_alter_usuarios_apellido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infoususario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colo_favorito', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50)),
                ('equipo_favorito', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='edad',
            field=models.IntegerField(default=True),
        ),
    ]
