# Generated by Django 4.0.3 on 2022-03-30 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0003_infoususario_remove_post_id_alter_post_titulo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infoususario',
            old_name='colo_favorito',
            new_name='color_favorito',
        ),
        migrations.AlterField(
            model_name='infoususario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
